-- Run this once in the Supabase SQL Editor.
-- Public visitors submit through the verified Edge Function. Only the approved admin email may read, update or delete enquiries directly.

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (
    char_length(email) between 3 and 254
    and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  discord_username text check (discord_username is null or char_length(discord_username) <= 100),
  project_type text not null check (char_length(project_type) between 1 and 80),
  runtime text not null check (char_length(runtime) between 1 and 120),
  budget text not null check (char_length(budget) between 1 and 80),
  deadline date,
  footage_link text check (
    footage_link is null
    or (char_length(footage_link) <= 1000 and footage_link ~* '^https?://')
  ),
  details text not null check (char_length(details) between 20 and 4000),
  status text not null default 'new' check (status in ('new', 'contacted', 'archived'))
);

alter table public.enquiries
add column if not exists discord_username text
check (discord_username is null or char_length(discord_username) <= 100);

alter table public.enquiries drop constraint if exists enquiries_email_check;
alter table public.enquiries add constraint enquiries_email_check check (
  char_length(email) between 3 and 254
  and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
);

alter table public.enquiries drop constraint if exists enquiries_footage_link_check;
alter table public.enquiries add constraint enquiries_footage_link_check check (
  footage_link is null
  or (char_length(footage_link) <= 1000 and footage_link ~* '^https?://')
);

create index if not exists enquiries_created_at_idx on public.enquiries (created_at desc);
create index if not exists enquiries_status_idx on public.enquiries (status);

alter table public.enquiries enable row level security;

drop policy if exists "Public can submit enquiries" on public.enquiries;
drop policy if exists "Admin can read enquiries" on public.enquiries;
drop policy if exists "Admin can update enquiries" on public.enquiries;
drop policy if exists "Admin can delete enquiries" on public.enquiries;

create policy "Admin can read enquiries"
on public.enquiries
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

create policy "Admin can update enquiries"
on public.enquiries
for update
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

create policy "Admin can delete enquiries"
on public.enquiries
for delete
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

revoke all on table public.enquiries from anon, authenticated;
grant select, update, delete on table public.enquiries to authenticated;
revoke all on sequence public.enquiries_id_seq from anon, authenticated;
