-- Run this once in the Supabase SQL Editor.
-- Public visitors submit through the verified Edge Function. Only the approved admin email may read, update or delete enquiries directly.

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (
    char_length(email) between 3 and 254
    and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  discord_username text check (discord_username is null or char_length(discord_username) <= 100),
  project_type text not null check (char_length(project_type) between 1 and 80),
  runtime text not null check (char_length(runtime) between 1 and 120),
  budget text not null check (char_length(budget) between 1 and 80),
  deadline date,
  footage_link text check (
    footage_link is null
    or (char_length(footage_link) <= 1000 and footage_link ~* '^https?://')
  ),
  details text not null check (char_length(details) between 20 and 4000),
  status text not null default 'new' check (status in ('new', 'contacted', 'archived')),
  internal_notes text check (internal_notes is null or char_length(internal_notes) <= 4000),
  quoted_price text check (quoted_price is null or char_length(quoted_price) <= 80),
  follow_up_on date,
  outcome text not null default 'pending' check (outcome in ('pending', 'won', 'lost', 'paused'))
);

alter table public.enquiries
add column if not exists discord_username text
check (discord_username is null or char_length(discord_username) <= 100);

alter table public.enquiries
add column if not exists internal_notes text
check (internal_notes is null or char_length(internal_notes) <= 4000);

alter table public.enquiries
add column if not exists quoted_price text
check (quoted_price is null or char_length(quoted_price) <= 80);

alter table public.enquiries add column if not exists follow_up_on date;

alter table public.enquiries
add column if not exists outcome text not null default 'pending'
check (outcome in ('pending', 'won', 'lost', 'paused'));

alter table public.enquiries drop constraint if exists enquiries_email_check;
alter table public.enquiries add constraint enquiries_email_check check (
  char_length(email) between 3 and 254
  and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
);

alter table public.enquiries drop constraint if exists enquiries_footage_link_check;
alter table public.enquiries add constraint enquiries_footage_link_check check (
  footage_link is null
  or (char_length(footage_link) <= 1000 and footage_link ~* '^https?://')
);

create index if not exists enquiries_created_at_idx on public.enquiries (created_at desc);
create index if not exists enquiries_status_idx on public.enquiries (status);

alter table public.enquiries enable row level security;

drop policy if exists "Public can submit enquiries" on public.enquiries;
drop policy if exists "Admin can read enquiries" on public.enquiries;
drop policy if exists "Admin can update enquiries" on public.enquiries;
drop policy if exists "Admin can delete enquiries" on public.enquiries;

create policy "Admin can read enquiries"
on public.enquiries
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

create policy "Admin can update enquiries"
on public.enquiries
for update
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

create policy "Admin can delete enquiries"
on public.enquiries
for delete
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

revoke all on table public.enquiries from anon, authenticated;
grant select, update, delete on table public.enquiries to authenticated;
revoke all on sequence public.enquiries_id_seq from anon, authenticated;

-- Anonymous, privacy-friendly site events. Public visitors can only submit
-- through the validated Edge Function; the owner can read the dashboard data.
create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null check (event_name in (
    'page_view', 'cta_click', 'showreel_play', 'work_open',
    'form_start', 'form_success', 'case_study_open'
  )),
  event_label text check (event_label is null or event_label ~ '^[a-z0-9_-]{1,60}$'),
  path text not null check (char_length(path) between 1 and 200),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 200),
  device_type text not null default 'unknown' check (device_type in ('desktop', 'tablet', 'mobile', 'unknown'))
);

alter table public.site_events
add column if not exists event_label text
check (event_label is null or event_label ~ '^[a-z0-9_-]{1,60}$');

create index if not exists site_events_created_at_idx on public.site_events (created_at desc);
create index if not exists site_events_name_idx on public.site_events (event_name, created_at desc);

alter table public.site_events enable row level security;
drop policy if exists "Admin can read site events" on public.site_events;

create policy "Admin can read site events"
on public.site_events
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'business.jxnn@gmail.com');

revoke all on table public.site_events from anon, authenticated;
grant select on table public.site_events to authenticated;
grant select, insert, delete on table public.site_events to service_role;
revoke all on sequence public.site_events_id_seq from anon, authenticated;
grant usage, select on sequence public.site_events_id_seq to service_role;

-- Server-only request limits and short-lived duplicate fingerprints.
create table if not exists public.request_rate_limits (
  key_hash text primary key check (char_length(key_hash) = 64),
  window_started_at timestamptz not null default now(),
  request_count integer not null default 1 check (request_count > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.submission_fingerprints (
  key_hash text primary key check (char_length(key_hash) = 64),
  created_at timestamptz not null default now()
);

alter table public.request_rate_limits enable row level security;
alter table public.submission_fingerprints enable row level security;
revoke all on table public.request_rate_limits from anon, authenticated;
revoke all on table public.submission_fingerprints from anon, authenticated;
grant select, insert, update, delete on table public.request_rate_limits to service_role;
grant select, insert, update, delete on table public.submission_fingerprints to service_role;

create or replace function public.check_request_rate_limit(
  p_key_hash text,
  p_max_requests integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  allowed boolean;
begin
  if char_length(p_key_hash) <> 64 or p_max_requests < 1 or p_window_seconds < 1 then
    return false;
  end if;

  insert into public.request_rate_limits (key_hash, window_started_at, request_count, updated_at)
  values (p_key_hash, now(), 1, now())
  on conflict (key_hash) do update
  set
    request_count = case
      when public.request_rate_limits.window_started_at <= now() - make_interval(secs => p_window_seconds)
        then 1
      else public.request_rate_limits.request_count + 1
    end,
    window_started_at = case
      when public.request_rate_limits.window_started_at <= now() - make_interval(secs => p_window_seconds)
        then now()
      else public.request_rate_limits.window_started_at
    end,
    updated_at = now()
  returning request_count <= p_max_requests into allowed;

  return coalesce(allowed, false);
end;
$$;

create or replace function public.reserve_submission_fingerprint(
  p_key_hash text,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  reserved_hash text;
begin
  if char_length(p_key_hash) <> 64 or p_window_seconds < 1 then
    return false;
  end if;

  delete from public.submission_fingerprints
  where key_hash = p_key_hash
    and created_at <= now() - make_interval(secs => p_window_seconds);

  insert into public.submission_fingerprints (key_hash)
  values (p_key_hash)
  on conflict do nothing
  returning key_hash into reserved_hash;

  return reserved_hash is not null;
end;
$$;

create or replace function public.release_submission_fingerprint(p_key_hash text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.submission_fingerprints where key_hash = p_key_hash;
$$;

revoke all on function public.check_request_rate_limit(text, integer, integer) from public, anon, authenticated;
revoke all on function public.reserve_submission_fingerprint(text, integer) from public, anon, authenticated;
revoke all on function public.release_submission_fingerprint(text) from public, anon, authenticated;
grant execute on function public.check_request_rate_limit(text, integer, integer) to service_role;
grant execute on function public.reserve_submission_fingerprint(text, integer) to service_role;
grant execute on function public.release_submission_fingerprint(text) to service_role;
